### ISSUE TITLE
How do I submit the other supporting files under one topic?

### ISSUE THREAD

**Issue by DasarathanSampath** [javascript-tutorial/ta.javascript.info#6]
![Capture](https://user-images.githubusercontent.com/24868297/80554149-d14b9c00-89e9-11ea-9538-ff98b23cd0f0.PNG)

Translation of article.md is submitted with a pull request title "Hello, World!".

How do I submit the other files (Image - Circled in red)?
Is it the same way, what I did for "article.md"?
What is the title of a pull request I have to give?

**Comment by sbkrish** [comment]
You can submit all the file changes with the same commit message. Just follow the same procedure for all the files inside each module. 
Note : Give the PR once the translation finished for all the files inside the module
